config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :posts
  get 'home/index'
  get 'home/about'
  get 'home/portfolio'
  get 'home/contact'

  root 'posts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, length: { maximum: 3000, minimum: 3 }
  belongs_to :user, counter_cache: true
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, length: { maximum: 512, minimum: 5 }
  belongs_to :user
  has_many :comments, as: :commentable
  has_many :commentators, through: :comments, source: :user

  scope :written_by_moderators, -> { joins(:user).where(users: {moderator: true })}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :commented_posts, through: :comments, source: :commentable, source_type: :Post
  has_many :commented_users, through: :comments, source: :commentable, source_type: :User

  validates :name, presence: true
  validates :name, length: { maximum: 30, minimum: 2 }
  validates :name, uniqueness: true

  before_destroy :log_before_destroy
  after_destroy  :log_after_destroy

  private

  def log_before_destroy
    Rails.logger.info "###### We are going to destroy user #{@name} ######"
  end

  def log_after_destroy
    Rails.logger.info "###### User #{@name} succesfully destroyed ######"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end

  def portfolio
  end

  def contact
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.includes(:user).page(params[:page]).per(5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = Post.find(params[:id]).comments.all.page(params[:page]).per(3)
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :user_id, :visible)
    end

  def get_random_imgs
    #TODO
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all.page(params[:page]).per(5)
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :moderator, :creator, :banned)
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.slim
h1 About!
p Dummy for about..
p

app/views/home/contact.html.slim
h1 Contact!
p Dummy for contact..
p

app/views/home/portfolio.html.slim
h1 Portfolio!
p Dummy for portfolio..
p

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>My Personally Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

  <!--<a href='/'> Home </a>&nbsp;-->
  <!--<a href='/home/about'> About </a>-->

  <div id="wrapper">

    <div id="menu">

      <ul>
        <!--class="current"-->
        <li><a href="../">Blog</a></li>
        <li><a href="../home/portfolio">Portfolio</a></li>
        <li><a href="../home/about">About Me</a></li>
        <li><a href="../home/contact">Contact</a></li>
        <% if user_signed_in? %>
            <li>
              <%= link_to(destroy_user_session_path, method: :delete) do %>
              <%= "#{t('label.log_out')}[#{current_user.name}]" %>
              <% end  %>
            </li>
        <% else %>
            <li><%= link_to "#{t('label.log_in')}", new_user_session_path %></li>
            <li><%= link_to "#{t('label.registration')}", new_user_registration_path %></li>
        <% end %>
      </ul>

    </div> <!-- end of menu -->

    <div id="left_column">

      <div id="sidebar">

        <h4>Categories</h4>
        <ul class="list">
          <li><a href="#" target="_parent">First cat</a></li>
          <li><a href="#" target="_parent">Second cat</a></li>
          <li><a href="#" target="_parent">Third cat</a></li>
          <li><a href="#" target="_parent">Fourth cat</a></li>
          <li><a href="#">Five cat</a></li>
          <li><a href="#">Six cat</a></li>
        </ul>

        <div class="cleaner_h40"></div>

      </div> <!-- end of sidebar -->
    </div> <!-- end of left_column -->

    <div id="right_column">
      <div id="main">

      <%= yield %>

      </div>

      <div class="cleaner"></div>
    </div>
    <!-- end of main -->

    <div class="cleaner_h20"></div>

    <div id="footer">
      Copyright © 2019 <a href="#">GeekBrains course</a> |
      <a href="#" target="_parent">Blog</a> by DSNick</a>
    </div>
    <div class="cleaner"></div>
    </div> <!-- end of warpper -->


  </body>
</html>

app/views/posts/_form.html.slim
= form_for post do |f|
  - if post.errors.any?
    #error_explanation
      h2 = "#{pluralize(post.errors.count, "error")} prohibited this post from being saved:"
      ul
        - post.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :visible
    = f.check_box :visible
  .actions = f.submit

app/views/posts/_post.html.slim
tr
  td = post.title
  td = post.body
  td = post.user.name
  td = post.visible
  td = link_to 'Show', post
  td = link_to 'Edit', edit_post_path(post)
  td = link_to 'Destroy', post, data: { confirm: 'Are you sure?' }, method: :delete

app/views/posts/edit.html.slim
h1 Editing post

== render 'form', post: @post

=> link_to 'Show', @post
'|
=< link_to 'Back', posts_path

app/views/posts/index.html.erb
    <% @posts.each do |post| %>
        <div class="post_section">
          <h2><%= link_to post.title, post %></h2>
          <%= post.created_at.strftime("%A, %d %B %Y %H:%M:%S") %> |
          <strong>Author:</strong> <%= post.user.name %><br><br>
          <!--<img src="images/image_01.jpg" alt="image 1" />-->
          <p><%= post.body.split.slice(0,30).join(" ") %> <br> <%= link_to 'Continue reading...', post %> </p>
        </div>
    <% end %>


    <%= link_to 'New Post', new_post_path %>
    <%= paginate @posts %>

app/views/posts/new.html.slim
h1 New post

== render 'form', post: @post

= link_to 'Back', posts_path

app/views/posts/show.html.slim
p#notice = notice

p
  strong Title:
  = @post.title
p
  strong Body:
  = @post.body
p
  strong User:
  = @post.user.name
p
  strong Visible:
  = @post.visible

p
  strong Comments:
  table
    - @comments.order(:created_at).each do |comment|
            tr
              td: b = comment.user.name
              td = comment.body

p
  = paginate @comments
p
=> link_to 'Edit', edit_post_path(@post)
'|
=< link_to 'Back', posts_path

app/views/shared/_header.html.slim
header
  ul
    - if user_signed_in?
      li
        span Hello, #{current_user.email}
      li
        = link_to 'Log out', destroy_user_session_path, method: :delete
    - else
      li
        = link_to 'Log in', new_user_session_path
      li
        = link_to 'Register', new_user_registration_path

app/views/users/_form.html.slim
= form_for user do |f|
  - if user.errors.any?
    #error_explanation
      h2 = "#{pluralize(user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :moderator
    = f.check_box :moderator
  .field
    = f.label :creator
    = f.check_box :creator
  .field
    = f.label :banned
    = f.check_box :banned
  .actions = f.submit

app/views/users/_user.html.slim
tr
  td = user.name
  td = user.email
  td = user.moderator
  td = user.creator
  td = user.banned
  td = link_to 'Show', user
  td = link_to 'Edit', edit_user_path(user)
  td = link_to 'Destroy', user, data: { confirm: 'Are you sure?' }, method: :delete

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 Listing users

table
  thead
    tr
      th Name
      th Email
      th Moderator
      th Creator
      th Banned
      th
      th
      th

  tbody
    = render partial: 'user', collection: @users


br

= link_to 'New User', new_user_path

p
  = paginate @users

app/views/users/new.html.slim
h1 New user

== render 'form', user: @user

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

p
  strong Name:
  = @user.name
p
  strong Email:
  = @user.email
p
  strong Moderator:
  = @user.moderator
p
  strong Creator:
  = @user.creator
p
  strong Banned:
  = @user.banned

=> link_to 'Edit', edit_user_path(@user)
'|
=< link_to 'Back', users_path